# Generated by Django 2.2.6 on 2020-01-27 23:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPRCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_zone', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=4)),
                ('url', models.URLField(unique=True)),
                ('geopoint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LPRCamera_allowed_plates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_plate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LPRCamera_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plate', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
